# normalizeme

One of the skills I would love to improve and is building usefull packages. I don't have much experience with this but I do enjoy the progress of making a function wich could be usefull for more people. The first function I wrote and actually still use in are is a min-max scaling normalisation function. To this end I descided to create a package to not have to redefine the function over and over again, and who knows maybe someone else might want to use it too!

The goal of normalizeme is to help with the normalization of data. It also contains a few functions to help plot a very simple graph, in case you want to visualize the normalized data quickly and a very insignificant data set just for the fun of it.  

The most important function of the package is minmax(). 

## Installation

You can install the development version of normalizeme from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("LunarEclipse112/normalizeme")
```